### ISSUE TITLE
updated 0.3.9 in hassio 2022.3.3 and stop working

### ISSUE THREAD

**Issue by lufegut** [JoDehli/PyLoxone#109] opened 2022-03-09 06:37 UTC
Error setting up entry PyLoxone for loxone
07:28:24 – (ERROR) PyLoxone (integración personalizada)
 
2022-03-09 07:27:10 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration loxone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-09 07:28:24 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
File "/config/custom_components/loxone/__init__.py", line 141, in async_setup_entry
File "/config/custom_components/loxone/miniserver.py", line 118, in async_setup
File "/config/custom_components/loxone/api.py", line 121, in getJson

**Comment by ianleuch** [comment] 2022-03-09 08:43
Same here

**Comment by ianleuch** [comment] 2022-03-09 08:43
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:77
Integration: PyLoxone (documentation, issues)
First occurred: 09:31:53 (1 occurrences)
Last logged: 09:31:53

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/adapters.py", line 42, in send
    ssl = httpcore.SSLConfig(cert=cert, verify=verify)
AttributeError: module 'httpcore' has no attribute 'SSLConfig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 141, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 110, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 77, in getJson
    api_resp = await requests.get(
  File "/usr/local/lib/python3.9/site-packages/requests_async/api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 320, in __aexit__
    await self.close()
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 311, in close
    await v.close()
  File "/usr/local/lib/python3.9/site-packages/requests_async/adapters.py", line 65, in close
    await self.pool.close()
TypeError: object NoneType can't be used in 'await' expression

**Comment by JoDehli** [comment] 2022-03-09 09:33
Please look at the other issues. I think you use the external address which is not working at the moment.

**Comment by lufegut** [comment] 2022-03-09 10:03
No, I use local IP.

**Comment by JoDehli** [comment] 2022-03-09 18:14
You can try the master branch and if this does not work you remove the integration complete and install it again. I can not do more because I can not reproduce the error. Sorry.

**Comment by lufegut** [comment] 2022-03-11 07:13
27 / 5.000
I have tried both options and it didn´t work.
Is there more information I can provide so you can identify the error?

**Comment by JoDehli** [comment] 2022-03-11 18:36
Can you paste log (only the loxone errors) with this settings: 

```yaml
logger:
  default: warning
  logs:
    homeassistant: warning
    homeassistant.helpers: warning
    custom_components.loxone: debug
    custom_components.loxone.api: debug
```
Maybe we see what is going wrong?

**Comment by lufegut** [comment] 2022-03-11 18:43
Este error se originó a partir de una integración personalizada.

Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:121
Integration: PyLoxone (documentation, issues)
First occurred: 9 de marzo de 2022, 22:14:07 (1 occurrences)
Last logged: 9 de marzo de 2022, 22:14:07

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 244, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 228, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 102, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 81, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 143, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 186, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 156, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 118, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 121, in getJson
    api_resp = await client.get("/jdev/cfg/apiKey")
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1736, in get
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1513, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1600, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

**Comment by JoDehli** [comment] 2022-03-11 18:48
Did it work before? Seem the miniserver is not responding?

**Comment by JoDehli** [comment] 2022-03-11 18:51
Can you paste it with the log settings I pasted?

**Comment by lufegut** [comment] 2022-03-11 19:41
> ¿Funcionó antes? ¿Parece que el miniservidor no responde?
Yes, it has worked for months until last week's hassio update
the miniserver responds from the loxone app, with the same local configuration



> ¿Puedes pegarlo con la configuración de registro que pegué?
where do i find that setting?

**Comment by JoDehli** [comment] 2022-03-11 19:45
In your yaml configuration file.

**Comment by lufegut** [comment] 2022-03-11 21:15
2022-03-11 21:15:57 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration loxone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-11 21:17:04 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
File "/config/custom_components/loxone/__init__.py", line 156, in async_setup_entry
File "/config/custom_components/loxone/miniserver.py", line 118, in async_setup
File "/config/custom_components/loxone/api.py", line 121, in getJson

**Comment by JoDehli** [comment] 2022-03-12 06:50
Didi you enable the log settings because it is the same output as before? 

Did you get the loxone config JSON via browser?

**Comment by lufegut** [comment] 2022-03-12 07:00
> ¿Habilitó la configuración de registro porque es el mismo resultado que antes?
Yes



> ¿Obtuviste el JSON de configuración de loxone a través del navegador?
No, I got it through HACS

**Comment by JoDehli** [comment] 2022-03-12 13:39
I meant can you get the Json via browser when you go to http://192.168.4.73:83/data/LoxAPP3.json
Normally you need to insert your username and password then you see your configuration of your loxone. The same info which the app gets an Pyloxone.

**Comment by lufegut** [comment] 2022-03-12 15:21
Yes I can

**Comment by JoDehli** [comment] 2022-03-13 10:30
Ok I changed my port to 83. And it worked. What you can try to give the homeassistant a new Ip address as a last try. 
Or install homeassistant on you main pc and try it from there. In the past some users had problems because there ip address was banned from the loxone miniserver due to too many connection fails.

**Comment by lufegut** [comment] 2022-03-15 08:25
I've tried both and it still doesn't work. :(

**Comment by Beiga11** [comment] 2022-03-15 15:57
Hi,

I am also having issues with the integration for about a week now. The miniserver works (gen 1, firmware 12.2.11.5).

It does not seem to be the same error message as @lufegut, but also seems to be linked to connectivity to the miniserver. I am able to retrieve the json via curl from the home assistant terminal.

This is what I have on the logs:

Error setting up entry PyLoxone for loxone

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/adapters.py", line 42, in send
    ssl = httpcore.SSLConfig(cert=cert, verify=verify)
AttributeError: module 'httpcore' has no attribute 'SSLConfig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 132, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 101, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 60, in getJson
    api_resp = await requests.get(url_api,
  File "/usr/local/lib/python3.9/site-packages/requests_async/api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 320, in __aexit__
    await self.close()
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 311, in close
    await v.close()
  File "/usr/local/lib/python3.9/site-packages/requests_async/adapters.py", line 65, in close
    await self.pool.close()
TypeError: object NoneType can't be used in 'await' expression

**Comment by JoDehli** [comment] 2022-03-15 16:20
@Beiga11 do you use hassio? Or a python installation.

**Comment by Beiga11** [comment] 2022-03-15 17:23
I've flashed hassos on a raspberry pi (I guess that means hassio as well, right..?)

**Comment by JoDehli** [comment] 2022-03-15 17:53
@Beiga11 Yes that was I meant. But then I really have not clue what is going wrong. Can you try a complete new install of hassos with a seperate sd card. Only to test pyloxone. I have the exact same setup and it works with no problems. And I can not reproduce the error.

**Comment by JoDehli** [comment] 2022-03-15 17:54
@Beiga11 do you have a big system? I mean a big loxone install?

**Comment by Beiga11** [comment] 2022-03-15 18:06
not sure what classifies as big :). Pyloxone shows 139 devices and 247 entities...

Can't try the new install at the moment. This has however been working very smoothly for a long period of time though and I can't think of any updates I have done that could have broken it...

**Comment by Beiga11** [comment] 2022-03-16 10:08
Hi, here's my loxone folder contents:

https://wetransfer.com/downloads/dad32df3eefa415067a446f0af26575620220315190616/129874

**Comment by JoDehli** [comment] 2022-03-16 18:02
@Beiga11 I was right it is a old version of the binding. This one can not work. Please download source direct from git and override the files int your config/custom_components/loxone. I do not know what happend. 

Please report if it is working.

**Comment by Beiga11** [comment] 2022-03-16 18:30
Hi, yes, I can confirm that overwritting from the github code and restarting Home Assistant has worked! Thanks!

**Comment by JoDehli** [comment] 2022-03-16 18:33
@Beiga11 and @lufegut glad that it works now. I close the issue now.

**Closed** 2022-03-16 18:34 UTC
